name: CI
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'

      - run: sbt app/Docker/publishLocal versionDump
        env:
          RELEASE: yesh

      - name: Deploy to Fly.io
        if: startsWith(github.ref, 'refs/tags/v') || (github.ref == 'refs/heads/main')        
        run: |
          curl -L https://fly.io/install.sh | sh

          export FLYCTL_INSTALL="$HOME/.fly"
          export PATH="$FLYCTL_INSTALL/bin:$PATH"

          flyctl deploy -i smithy4s-fullstack:$(cat version)

